import type { CastMember } from '@/types/movie';

export const cast: CastMember[] = [
  {
    actorName: 'Neve Campbell',
    characterName: 'Sidney Prescott',
    role: 'lead',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/neve-campbell.jpg',
  },
  {
    actorName: 'Courteney Cox',
    characterName: 'Gale Weathers-Riley',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/courteney-cox.jpg',
  },
  {
    actorName: 'David Arquette',
    characterName: 'Sheriff Dewey Riley',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/david-arquette.jpg',
  },
  {
    actorName: 'Emma Roberts',
    characterName: 'Jill Roberts',
    role: 'supporting',
    isGhostface: true,
    isFranchiseRegular: false,
    headshot: '/images/cast/emma-roberts.jpg',
  },
  {
    actorName: 'Hayden Panettiere',
    characterName: 'Kirby Reed',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/hayden-panettiere.jpg',
  },
  {
    actorName: 'Rory Culkin',
    characterName: 'Charlie Walker',
    role: 'supporting',
    isGhostface: true,
    isFranchiseRegular: false,
    headshot: '/images/cast/rory-culkin.jpg',
  },
  {
    actorName: 'Marley Shelton',
    characterName: 'Deputy Judy Hicks',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/marley-shelton.jpg',
  },
  {
    actorName: 'Erik Knudsen',
    characterName: 'Robbie Mercer',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/placeholder.svg',
  },
  {
    actorName: 'Nico Tortorella',
    characterName: 'Trevor Sheldon',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/placeholder.svg',
  },
  {
    actorName: 'Marielle Jaffe',
    characterName: 'Olivia Morris',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/placeholder.svg',
  },
  {
    actorName: 'Alison Brie',
    characterName: 'Rebecca Walters',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/alison-brie.jpg',
  },
  {
    actorName: 'Anthony Anderson',
    characterName: 'Deputy Anthony Perkins',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/anthony-anderson.jpg',
  },
  {
    actorName: 'Adam Brody',
    characterName: 'Deputy Ross Hoss',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/adam-brody.jpg',
  },
  {
    actorName: 'Mary McDonnell',
    characterName: 'Kate Roberts',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/mary-mcdonnell.jpg',
  },
  {
    actorName: 'Anna Paquin',
    characterName: 'Rachel',
    role: 'cameo',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/anna-paquin.jpg',
  },
  {
    actorName: 'Kristen Bell',
    characterName: 'Chloe',
    role: 'cameo',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/kristen-bell.jpg',
  },
  {
    actorName: 'Lucy Hale',
    characterName: 'Sherrie',
    role: 'cameo',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/lucy-hale.jpg',
  },
  {
    actorName: 'Shenae Grimes-Beech',
    characterName: 'Trudie',
    role: 'cameo',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/placeholder.svg',
  },
  {
    actorName: 'Aimee Teegarden',
    characterName: 'Jenny Randall',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/placeholder.svg',
  },
  {
    actorName: 'Britt Robertson',
    characterName: 'Marnie Cooper',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/britt-robertson.jpg',
  },
  {
    actorName: 'Roger L. Jackson',
    characterName: 'Voice of Ghostface',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/roger-l-jackson.jpg',
  },
];
