import type { CastMember } from '@/types/movie';

export const cast: CastMember[] = [
  {
    actorName: 'Neve Campbell',
    characterName: 'Sidney Prescott',
    role: 'lead',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/neve-campbell.jpg',
  },
  {
    actorName: 'Courteney Cox',
    characterName: 'Gale Weathers',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/courteney-cox.jpg',
  },
  {
    actorName: 'Isabel May',
    characterName: 'Tatum Evans',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/isabel-may.jpg',
  },
  {
    actorName: 'Joel McHale',
    characterName: 'Mark Evans',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/joel-mchale.jpg',
  },
  {
    actorName: 'Jasmin Savoy Brown',
    characterName: 'Mindy Meeks-Martin',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/jasmin-savoy-brown.jpg',
  },
  {
    actorName: 'Mason Gooding',
    characterName: 'Chad Meeks-Martin',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/mason-gooding.jpg',
  },
  {
    actorName: 'Matthew Lillard',
    characterName: 'Stu Macher (deepfake)',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/matthew-lillard.jpg',
  },
  {
    actorName: 'Anna Camp',
    characterName: 'Jessica Bowden',
    role: 'supporting',
    isGhostface: true,
    isFranchiseRegular: false,
    headshot: '/images/cast/anna-camp.jpg',
  },
  {
    actorName: 'Ethan Embry',
    characterName: 'Marco',
    role: 'supporting',
    isGhostface: true,
    isFranchiseRegular: false,
    headshot: '/images/cast/ethan-embry.jpg',
  },
  {
    actorName: 'Celeste O\'Connor',
    characterName: 'Chloe',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/celeste-oconnor.jpg',
  },
  {
    actorName: 'Asa Germann',
    characterName: 'Lucas Bowden',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/asa-germann.jpg',
  },
  {
    actorName: 'Sam Rechner',
    characterName: 'Ben',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/sam-rechner.jpg',
  },
  {
    actorName: 'Jimmy Tatro',
    characterName: 'Scott',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/jimmy-tatro.jpg',
  },
  {
    actorName: 'Michelle Randolph',
    characterName: 'Madison',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/michelle-randolph.jpg',
  },
  {
    actorName: 'Roger L. Jackson',
    characterName: 'Voice of Ghostface',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/roger-l-jackson.jpg',
  },
];
