import type { CastMember } from '@/types/movie';

export const cast: CastMember[] = [
  {
    actorName: 'Neve Campbell',
    characterName: 'Sidney Prescott',
    role: 'lead',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/neve-campbell.jpg',
  },
  {
    actorName: 'Courteney Cox',
    characterName: 'Gale Weathers',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/courteney-cox.jpg',
  },
  {
    actorName: 'David Arquette',
    characterName: 'Dewey Riley',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/david-arquette.jpg',
  },
  {
    actorName: 'Jamie Kennedy',
    characterName: 'Randy Meeks',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/jamie-kennedy.jpg',
  },
  {
    actorName: 'Timothy Olyphant',
    characterName: 'Mickey Altieri',
    role: 'supporting',
    isGhostface: true,
    isFranchiseRegular: false,
    headshot: '/images/cast/timothy-olyphant.jpg',
  },
  {
    actorName: 'Laurie Metcalf',
    characterName: 'Debbie Salt / Nancy Loomis',
    role: 'supporting',
    isGhostface: true,
    isFranchiseRegular: false,
    headshot: '/images/cast/laurie-metcalf.jpg',
  },
  {
    actorName: "Jerry O'Connell",
    characterName: 'Derek Feldman',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/jerry-oconnell.jpg',
  },
  {
    actorName: 'Jada Pinkett Smith',
    characterName: 'Maureen Evans',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/jada-pinkett-smith.jpg',
  },
  {
    actorName: 'Omar Epps',
    characterName: 'Phil Stevens',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/omar-epps.jpg',
  },
  {
    actorName: 'Sarah Michelle Gellar',
    characterName: 'Cici Cooper',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/sarah-michelle-gellar.jpg',
  },
  {
    actorName: 'Liev Schreiber',
    characterName: 'Cotton Weary',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/liev-schreiber.jpg',
  },
  {
    actorName: 'Elise Neal',
    characterName: 'Hallie McDaniel',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/elise-neal.jpg',
  },
  {
    actorName: 'Duane Martin',
    characterName: 'Joel Jones',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/placeholder.svg',
  },
  {
    actorName: 'Rebecca Gayheart',
    characterName: 'Lois Murphy',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/rebecca-gayheart.jpg',
  },
  {
    actorName: 'Portia de Rossi',
    characterName: 'Murphy Stevens',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/portia-de-rossi.jpg',
  },
  {
    actorName: 'Roger L. Jackson',
    characterName: 'Voice of Ghostface',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/roger-l-jackson.jpg',
  },
];
