import type { CastMember } from '@/types/movie';

export const cast: CastMember[] = [
  {
    actorName: 'Melissa Barrera',
    characterName: 'Sam Carpenter',
    role: 'lead',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/melissa-barrera.jpg',
  },
  {
    actorName: 'Jenna Ortega',
    characterName: 'Tara Carpenter',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/jenna-ortega.jpg',
  },
  {
    actorName: 'Jack Quaid',
    characterName: 'Richie Kirsch',
    role: 'supporting',
    isGhostface: true,
    isFranchiseRegular: false,
    headshot: '/images/cast/jack-quaid.jpg',
  },
  {
    actorName: 'Neve Campbell',
    characterName: 'Sidney Prescott',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/neve-campbell.jpg',
  },
  {
    actorName: 'Courteney Cox',
    characterName: 'Gale Weathers',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/courteney-cox.jpg',
  },
  {
    actorName: 'David Arquette',
    characterName: 'Dewey Riley',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/david-arquette.jpg',
  },
  {
    actorName: 'Mikey Madison',
    characterName: 'Amber Freeman',
    role: 'supporting',
    isGhostface: true,
    isFranchiseRegular: false,
    headshot: '/images/cast/mikey-madison.jpg',
  },
  {
    actorName: 'Dylan Minnette',
    characterName: 'Wes Hicks',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/dylan-minnette.jpg',
  },
  {
    actorName: 'Mason Gooding',
    characterName: 'Chad Meeks-Martin',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/mason-gooding.jpg',
  },
  {
    actorName: 'Jasmin Savoy Brown',
    characterName: 'Mindy Meeks-Martin',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/jasmin-savoy-brown.jpg',
  },
  {
    actorName: 'Sonia Ammar',
    characterName: 'Liv McKenzie',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/sonia-ammar.jpg',
  },
  {
    actorName: 'Kyle Gallner',
    characterName: 'Vince Schneider',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/kyle-gallner.jpg',
  },
  {
    actorName: 'Marley Shelton',
    characterName: 'Sheriff Judy Hicks',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/marley-shelton.jpg',
  },
  {
    actorName: 'Skeet Ulrich',
    characterName: 'Billy Loomis (hallucination)',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/skeet-ulrich.jpg',
  },
  {
    actorName: 'Roger L. Jackson',
    characterName: 'Voice of Ghostface',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/roger-l-jackson.jpg',
  },
  {
    actorName: 'Heather Matarazzo',
    characterName: 'Martha Meeks',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/heather-matarazzo.jpg',
  },
];
