import type { CastMember } from '@/types/movie';

export const cast: CastMember[] = [
  {
    actorName: 'Neve Campbell',
    characterName: 'Sidney Prescott',
    role: 'lead',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/neve-campbell.jpg',
  },
  {
    actorName: 'Courteney Cox Arquette',
    characterName: 'Gale Weathers',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/courteney-cox.jpg',
  },
  {
    actorName: 'David Arquette',
    characterName: 'Dewey Riley',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/david-arquette.jpg',
  },
  {
    actorName: 'Scott Foley',
    characterName: 'Roman Bridger',
    role: 'supporting',
    isGhostface: true,
    isFranchiseRegular: false,
    headshot: '/images/cast/scott-foley.jpg',
  },
  {
    actorName: 'Patrick Dempsey',
    characterName: 'Detective Mark Kincaid',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/patrick-dempsey.jpg',
  },
  {
    actorName: 'Parker Posey',
    characterName: 'Jennifer Jolie',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/parker-posey.jpg',
  },
  {
    actorName: 'Lance Henriksen',
    characterName: 'John Milton',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/lance-henriksen.jpg',
  },
  {
    actorName: 'Jenny McCarthy',
    characterName: 'Sarah Darling',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/jenny-mccarthy.jpg',
  },
  {
    actorName: 'Emily Mortimer',
    characterName: 'Angelina Tyler',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/emily-mortimer.jpg',
  },
  {
    actorName: 'Matt Keeslar',
    characterName: 'Tom Prinze',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/placeholder.svg',
  },
  {
    actorName: 'Deon Richmond',
    characterName: 'Tyson Fox',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/deon-richmond.jpg',
  },
  {
    actorName: 'Patrick Warburton',
    characterName: 'Steven Stone',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/patrick-warburton.jpg',
  },
  {
    actorName: 'Liev Schreiber',
    characterName: 'Cotton Weary',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/liev-schreiber.jpg',
  },
  {
    actorName: 'Kelly Rutherford',
    characterName: 'Christine Hamilton',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/kelly-rutherford.jpg',
  },
  {
    actorName: 'Jamie Kennedy',
    characterName: 'Randy Meeks (video cameo)',
    role: 'cameo',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/jamie-kennedy.jpg',
  },
  {
    actorName: 'Roger L. Jackson',
    characterName: 'Voice of Ghostface',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/roger-l-jackson.jpg',
  },
];
