import type { CastMember } from '@/types/movie';

export const cast: CastMember[] = [
  {
    actorName: 'Neve Campbell',
    characterName: 'Sidney Prescott',
    role: 'lead',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/neve-campbell.jpg',
  },
  {
    actorName: 'Courteney Cox',
    characterName: 'Gale Weathers',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/courteney-cox.jpg',
  },
  {
    actorName: 'David Arquette',
    characterName: "Deputy Dwight 'Dewey' Riley",
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/david-arquette.jpg',
  },
  {
    actorName: 'Skeet Ulrich',
    characterName: 'Billy Loomis',
    role: 'supporting',
    isGhostface: true,
    isFranchiseRegular: true,
    headshot: '/images/cast/skeet-ulrich.jpg',
  },
  {
    actorName: 'Matthew Lillard',
    characterName: 'Stu Macher',
    role: 'supporting',
    isGhostface: true,
    isFranchiseRegular: false,
    headshot: '/images/cast/matthew-lillard.jpg',
  },
  {
    actorName: 'Rose McGowan',
    characterName: 'Tatum Riley',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/rose-mcgowan.jpg',
  },
  {
    actorName: 'Drew Barrymore',
    characterName: 'Casey Becker',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/drew-barrymore.jpg',
  },
  {
    actorName: 'Jamie Kennedy',
    characterName: 'Randy Meeks',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/jamie-kennedy.jpg',
  },
  {
    actorName: 'W. Earl Brown',
    characterName: 'Kenny Jones',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/w-earl-brown.jpg',
  },
  {
    actorName: 'Roger L. Jackson',
    characterName: 'Voice of Ghostface',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/roger-l-jackson.jpg',
  },
  {
    actorName: 'Liev Schreiber',
    characterName: 'Cotton Weary',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/liev-schreiber.jpg',
  },
  {
    actorName: 'Henry Winkler',
    characterName: 'Principal Arthur Himbry',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/henry-winkler.jpg',
  },
  {
    actorName: 'Lawrence Hecht',
    characterName: 'Neil Prescott',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/placeholder.svg',
  },
  {
    actorName: 'Kevin Patrick Walls',
    characterName: 'Steve Orth',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/placeholder.svg',
  },
  {
    actorName: 'Joseph Whipp',
    characterName: 'Sheriff Burke',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/placeholder.svg',
  },
  {
    actorName: 'Frances Lee McCain',
    characterName: 'Mrs. Riley',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/placeholder.svg',
  },
  {
    actorName: 'C.W. Morgan',
    characterName: 'Hank Loomis',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/placeholder.svg',
  },
];
