import type { CastMember } from '@/types/movie';

export const cast: CastMember[] = [
  {
    actorName: 'Melissa Barrera',
    characterName: 'Sam Carpenter',
    role: 'lead',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/melissa-barrera.jpg',
  },
  {
    actorName: 'Jenna Ortega',
    characterName: 'Tara Carpenter',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/jenna-ortega.jpg',
  },
  {
    actorName: 'Courteney Cox',
    characterName: 'Gale Weathers',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/courteney-cox.jpg',
  },
  {
    actorName: 'Jasmin Savoy Brown',
    characterName: 'Mindy Meeks-Martin',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/jasmin-savoy-brown.jpg',
  },
  {
    actorName: 'Mason Gooding',
    characterName: 'Chad Meeks-Martin',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/mason-gooding.jpg',
  },
  {
    actorName: 'Dermot Mulroney',
    characterName: 'Detective Wayne Bailey',
    role: 'supporting',
    isGhostface: true,
    isFranchiseRegular: false,
    headshot: '/images/cast/dermot-mulroney.jpg',
  },
  {
    actorName: 'Jack Champion',
    characterName: 'Ethan Landry',
    role: 'supporting',
    isGhostface: true,
    isFranchiseRegular: false,
    headshot: '/images/cast/jack-champion.jpg',
  },
  {
    actorName: 'Liana Liberato',
    characterName: 'Quinn Bailey',
    role: 'supporting',
    isGhostface: true,
    isFranchiseRegular: false,
    headshot: '/images/cast/liana-liberato.jpg',
  },
  {
    actorName: 'Hayden Panettiere',
    characterName: 'Kirby Reed',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/hayden-panettiere.jpg',
  },
  {
    actorName: 'Josh Segarra',
    characterName: 'Danny Brackett',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/josh-segarra.jpg',
  },
  {
    actorName: 'Devyn Nekoda',
    characterName: 'Anika Kayoko',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/devyn-nekoda.jpg',
  },
  {
    actorName: 'Tony Revolori',
    characterName: 'Jason Carvey',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/tony-revolori.jpg',
  },
  {
    actorName: 'Samara Weaving',
    characterName: 'Laura Crane',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/samara-weaving.jpg',
  },
  {
    actorName: 'Henry Czerny',
    characterName: 'Dr. Christopher Stone',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: false,
    headshot: '/images/cast/henry-czerny.jpg',
  },
  {
    actorName: 'Skeet Ulrich',
    characterName: 'Billy Loomis (hallucination)',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/skeet-ulrich.jpg',
  },
  {
    actorName: 'Roger L. Jackson',
    characterName: 'Voice of Ghostface',
    role: 'supporting',
    isGhostface: false,
    isFranchiseRegular: true,
    headshot: '/images/cast/roger-l-jackson.jpg',
  },
];
