import type { Movie, MovieSlug } from '@/types/movie';

export const movies: Movie[] = [
  {
    id: 'scream-1996' as MovieSlug,
    slug: 'scream-1996' as MovieSlug,
    title: 'Scream',
    year: 1996,
    director: 'Wes Craven',
    runtime: 111,
    rating: 'R',
    imdbScore: 7.4,
    imdbId: 'tt0117571',
    tmdbId: 4232,
    tagline: 'Someone has taken their love of scary movies one step too far.',
    posterPath: '/images/posters/scream-1996.jpg',
    backdropPath: '/images/posters/scream-1996-backdrop.jpg',
    posterBlurHash: '',
    franchiseOrder: 1,
  },
  {
    id: 'scream-2-1997' as MovieSlug,
    slug: 'scream-2-1997' as MovieSlug,
    title: 'Scream 2',
    year: 1997,
    director: 'Wes Craven',
    runtime: 120,
    rating: 'R',
    imdbScore: 6.3,
    imdbId: 'tt0120082',
    tmdbId: 4233,
    tagline: 'Someone has taken their love of sequels one step too far.',
    posterPath: '/images/posters/scream-2-1997.jpg',
    backdropPath: '/images/posters/scream-2-1997-backdrop.jpg',
    posterBlurHash: '',
    franchiseOrder: 2,
  },
  {
    id: 'scream-3-2000' as MovieSlug,
    slug: 'scream-3-2000' as MovieSlug,
    title: 'Scream 3',
    year: 2000,
    director: 'Wes Craven',
    runtime: 116,
    rating: 'R',
    imdbScore: 5.7,
    imdbId: 'tt0134084',
    tmdbId: 4234,
    tagline: 'In the final chapter, the past will come back to haunt you.',
    posterPath: '/images/posters/scream-3-2000.jpg',
    backdropPath: '/images/posters/scream-3-2000-backdrop.jpg',
    posterBlurHash: '',
    franchiseOrder: 3,
  },
  {
    id: 'scream-4-2011' as MovieSlug,
    slug: 'scream-4-2011' as MovieSlug,
    title: 'Scream 4',
    year: 2011,
    director: 'Wes Craven',
    runtime: 111,
    rating: 'R',
    imdbScore: 6.2,
    imdbId: 'tt1262416',
    tmdbId: 41446,
    tagline: 'New decade. New rules.',
    posterPath: '/images/posters/scream-4-2011.jpg',
    backdropPath: '/images/posters/scream-4-2011-backdrop.jpg',
    posterBlurHash: '',
    franchiseOrder: 4,
  },
  {
    id: 'scream-5-2022' as MovieSlug,
    slug: 'scream-5-2022' as MovieSlug,
    title: 'Scream',
    year: 2022,
    director: 'Matt Bettinelli-Olpin & Tyler Gillett',
    runtime: 114,
    rating: 'R',
    imdbScore: 6.3,
    imdbId: 'tt11245972',
    tmdbId: 646385,
    tagline: 'It\'s always someone you know.',
    posterPath: '/images/posters/scream-5-2022.jpg',
    backdropPath: '/images/posters/scream-5-2022-backdrop.jpg',
    posterBlurHash: '',
    franchiseOrder: 5,
  },
  {
    id: 'scream-vi-2023' as MovieSlug,
    slug: 'scream-vi-2023' as MovieSlug,
    title: 'Scream VI',
    year: 2023,
    director: 'Matt Bettinelli-Olpin & Tyler Gillett',
    runtime: 123,
    rating: 'R',
    imdbScore: 6.4,
    imdbId: 'tt17663992',
    tmdbId: 934433,
    tagline: 'New York. New rules.',
    posterPath: '/images/posters/scream-vi-2023.jpg',
    backdropPath: '/images/posters/scream-vi-2023-backdrop.jpg',
    posterBlurHash: '',
    franchiseOrder: 6,
  },
];
